site_name: The Cassandra Files
use_directory_urls: false

plugins: []

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Rationale: index.md
  - The record: institutional-timeline.md

extra_css:
  - stylesheets/extra.css